export const CLOCK_CONSTANTS = {
    // numbers
    CENTER_OFFSET : 50, //CENTER POSITION OF CLOCK
    RADIUS : 45, // DISTANCE OF NUMBER
    DEGREES_PER_HOUR: 30, // DEGREE PER HOUR
    DEG_TO_RAD: Math.PI / 180, // DEGREES TO RADIANS CONVERSION

    // hands
    DEGREES_PER_MINUTE_SECOND: 6, // DEGREE PER MINUTE
    MINUTE_ADJUSTMENT: 0.5, // MINUTE HAND ADJUSTMENT
    SECOND_ADJUSTMENT: 0.1, // SECOND HAND ADJUSTMENT
    OFFSET_ROTATION: 180, // OFFSET ROTATION FOR HANDS
}